asg:
  name: kafka-dedicated
  max: 5
  min: 1
  desired: 3
  subnets: "subnet-0fb3f183f38ba186f,subnet-0811b038c2d9a27ef,subnet-07f40d97bcba2e399"
  tags:
    CreatedBy: AsgOperator
  
ec2:
  namePrefix: kafka-dedicated-worker
  launchTemplate:
    tags:
      CreatedBy: AsgOperator
      Nodegroup: kafka-dedicated
      kubernetes.io/cluster/tally: owned
      kubernetes.io/cluser-autoscaler/tally: owned
      kubernetes.io/cluser-autoscaler/enabled: true
    name: kafka-dedicated
    publicIps: true
    instanceType: t2.medium
    keyName: talhaverse
    securityGroups:
      - sg-03d8fd9741d919892
    iamInstanceProfile: eks-d8b7bb57-be52-35d8-0057-b95d4f558523
    ebs:
      volumeSize: 50
      volumeType: gp2
    userData: "#!/bin/bash \n
      /etc/eks/bootstrap.sh tally  --apiserver-endpoint https://5EDBD7586B5C079A56734EF93A1A12B0.gr7.us-east-1.eks.amazonaws.com --b64-cluster-ca LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ERXdOVEUzTURZek1Gb1hEVE13TURFd01qRTNNRFl6TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUZMCm1BV3A3aEFyc2dMeVJ6NlRHQjR4UmFBME5RV3cvSk9JUnlXbndvRFFjLzNiWVhUeWE4cHRXMm4rdnRIYTc4c3IKOXd0L01QNWRZSnlsRWFQR0s5c3hXa1BqaS9odnRkMUlpbFVFNEIrdWVzVmN3aGZybzkzNTBwZXhramJyTUJNUgoxZmczQTE4Y2FFT1VVSGVSUVp2dW14aGZ3TmsrS21SdTNTT0gydmpyS0hPK2F6c2hKZXpFc3BXTDJpNVpCZzNvCkQzSnlnemdYVy8vcHpqK0EvUGg1cC8wOE9lRlc3S1N3OFdVS2paUmkvdVdMUDJQUmVwcWxna1c2UVFtekg0WHUKR0tBVEE2RXEvbFFEazJZYTlsZmlkTzJ0MjRncTMyd2xYRStvQ2NnZTdBMnNLRjZ4aTkrRXl4MFpydmlUQXNvMgppVUFWbUdiSGRRM2Q5bmhrN05zQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMRis4d2xISUpjbC9sNlJRbTFkZzFSNkFZVFkKSHhxM2pKSitsTUlLYjMzdFd0T1dXYkw0MU5nVHZjZ2ErZUJDSXdUaFFSK0FJQ0huZi9udW9vdDhXLzlGM3g0awpteCsrMTRhamVJdDB2R0xxdE1VbE9QZ3plRTNzOUVsYUhxK2piS3loN25KbWMvUis2Z2hiTTJpQnRUNmNJSFViCk1IOUZHYm9xazBiUTJXRzNkajc2ajdrZks4UFYvblVRSlVUNCs2SndhNXJoditMMXBnL2VFZUFWUlFTajAvY3gKbmcrSjBWZTJ3TTNjRi9SVHo5bnoxMWxIZGJrakNERGV5cCtrUHF1ZmpQV1ZxTnNBL3hDR2paZ2NCOXd6NThyRQpOeEVUTHRUOGZaamE3c3JGU3BUVGtHeE50bXdwSWRLNjVmWmRjc2Q4eGIzL3ZhKzRZL252aGoyelluMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= \n
      systemctl restart kubelet \n"
ssm:
  autoAmiUpgrade: false